import express from 'express';
import cors from 'cors';
import axios from 'axios';
import dotenv from 'dotenv';
import { LRUCache } from 'lru-cache';

dotenv.config({ path: '.env.local' });

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3001;
const API_KEY = process.env.VITE_YOUTUBE_API_KEY;

// LRU 캐시 설정: 최대 1000개의 검색 결과만 메모리에 보관
const options = {
  max: 1000, // 최대 저장할 항목(검색 결과) 개수
  ttl: 1000 * 60 * 60 * 24, // 24시간 동안 유지
};
const cache = new LRUCache(options);

const getPublishedAfter = (p) => {
  const d = new Date();
  if (p === '1w') d.setDate(d.getDate() - 7);
  else if (p === '1m') d.setMonth(d.getMonth() - 1);
  else if (p === '3m') d.setMonth(d.getMonth() - 3);
  else return null;
  return d.toISOString();
};

app.get('/api/videos', async (req, res) => {
  const { searchQuery, overridePeriod } = req.query;

  if (!searchQuery) {
    return res.status(400).json({ error: 'searchQuery is required' });
  }

  if (!API_KEY) {
    return res.status(500).json({ error: 'YouTube API Key is missing on the server' });
  }

  const cacheKey = `${searchQuery}_${overridePeriod}`;
  
  const cachedData = cache.get(cacheKey);
  if (cachedData) {
    console.log(`[Cache Hit] ${cacheKey} (Total cached items: ${cache.size})`);
    return res.json(cachedData);
  }

  console.log(`[Cache Miss] Fetching data for: ${cacheKey}`);

  try {
    const publishedAfter = getPublishedAfter(overridePeriod);
    const searchParams = { part: 'snippet', q: searchQuery, maxResults: 50, type: 'video', key: API_KEY };
    if (publishedAfter) searchParams.publishedAfter = publishedAfter;

    const searchRes = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: searchParams
    });
    const items = searchRes.data.items || [];

    if (items.length === 0) {
      return res.json([]);
    }

    const videoIds = items.map(item => item.id.videoId).join(',');
    const channelIds = [...new Set(items.map(item => item.snippet.channelId))].join(',');

    const videoRes = await axios.get('https://www.googleapis.com/youtube/v3/videos', {
      params: { part: 'statistics', id: videoIds, key: API_KEY }
    });
    const channelRes = await axios.get('https://www.googleapis.com/youtube/v3/channels', {
      params: { part: 'statistics', id: channelIds, key: API_KEY }
    });

    const channelMap = {};
    channelRes.data.items.forEach(c => { channelMap[c.id] = parseInt(c.statistics.subscriberCount); });

    const statsMap = {};
    videoRes.data.items.forEach(v => { statsMap[v.id] = parseInt(v.statistics.viewCount); });

    const enrichedVideos = items
      .filter(item => {
        const isTopic = item.snippet.channelTitle.endsWith(' - Topic');
        const isAutoGenerated = item.snippet.description && item.snippet.description.includes('Auto-generated by YouTube');
        return !isTopic && !isAutoGenerated;
      })
      .map(item => {
        const views = statsMap[item.id.videoId] || 0;
        const subs = channelMap[item.snippet.channelId] || 1;
        return {
          id: item.id.videoId,
          title: item.snippet.title,
          thumbnail: item.snippet.thumbnails.high.url,
          channelTitle: item.snippet.channelTitle,
          views,
          subscribers: subs,
          ratio: parseFloat((views / subs).toFixed(2)),
          publishedAt: item.snippet.publishedAt
        };
      }).sort((a, b) => b.ratio - a.ratio);

    // 캐시에 저장
    cache.set(cacheKey, enrichedVideos);

    res.json(enrichedVideos);
  } catch (error) {
    console.error('API Fetch Error:', error?.response?.data || error.message);
    res.status(500).json({ error: 'Failed to fetch data from YouTube API' });
  }
});

app.listen(PORT, () => {
  console.log(`Server is running closely on http://localhost:${PORT}`);
});
