import express from 'express';
import cors from 'cors';
import axios from 'axios';
import dotenv from 'dotenv';
import { LRUCache } from 'lru-cache';

dotenv.config({ path: '.env.local' });

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3001;
const API_KEY = process.env.VITE_YOUTUBE_API_KEY;

// 기본 제공 카테고리 (캐시에서 밀려나지 않도록 별도 관리)
const defaultQueries = [
  '코딩 브이로그',
  '일상|브이로그|vlog',
  '게임|리뷰|플레이',
  '강아지|고양이|동물',
  '이슈|뉴스|알아보기|꿀팁',
  '먹방|요리|레시피|mukbang',
  '여행|가볼만한곳|핫플'
];

// 고정 캐시: 기본 카테고리는 조회 빈도가 높으므로 밀려나지 않게 따로 저장
const fixedCache = new LRUCache({
  max: 100, // 카테고리 * 시간 조합을 다 합쳐도 100개면 충분
  ttl: 1000 * 60 * 60 * 24, // 24시간
});

// 일반 캐시: 단순 사용자 검색 (1000개 초과 시 오래된 것부터 삭제)
const cache = new LRUCache({
  max: 1000,
  ttl: 1000 * 60 * 60 * 24, // 24시간
});

const getPublishedAfter = (p) => {
  const d = new Date();
  if (p === '1w') d.setDate(d.getDate() - 7);
  else if (p === '1m') d.setMonth(d.getMonth() - 1);
  else if (p === '3m') d.setMonth(d.getMonth() - 3);
  else return null;
  return d.toISOString();
};

app.get('/api/videos', async (req, res) => {
  const { searchQuery, overridePeriod } = req.query;

  if (!searchQuery) {
    return res.status(400).json({ error: 'searchQuery is required' });
  }

  if (!API_KEY) {
    return res.status(500).json({ error: 'YouTube API Key is missing on the server' });
  }

  const cacheKey = `v2_${searchQuery}_${overridePeriod}`;
  
  // 기본 카테고리인지 확인하고 캐시를 나눔
  const isDefaultQuery = defaultQueries.includes(searchQuery);
  const targetCache = isDefaultQuery ? fixedCache : cache;
  
  const cachedData = targetCache.get(cacheKey);
  if (cachedData) {
    console.log(`[Cache Hit] ${cacheKey} (Target: ${isDefaultQuery ? 'Fixed' : 'Normal'}, Size: ${targetCache.size})`);
    return res.json(cachedData);
  }

  console.log(`[Cache Miss] Fetching data for: ${cacheKey}`);

  try {
    const publishedAfter = getPublishedAfter(overridePeriod);
    const searchParams = { part: 'snippet', q: searchQuery, maxResults: 50, type: 'video', key: API_KEY };
    if (publishedAfter) searchParams.publishedAfter = publishedAfter;

    const searchRes = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: searchParams
    });
    const items = searchRes.data.items || [];

    if (items.length === 0) {
      return res.json([]);
    }

    const videoIds = items.map(item => item.id.videoId).join(',');
    const channelIds = [...new Set(items.map(item => item.snippet.channelId))].join(',');

    const videoRes = await axios.get('https://www.googleapis.com/youtube/v3/videos', {
      params: { part: 'statistics,snippet', id: videoIds, key: API_KEY }
    });
    const channelRes = await axios.get('https://www.googleapis.com/youtube/v3/channels', {
      params: { part: 'statistics', id: channelIds, key: API_KEY }
    });

    const categoryMap = {
      '1': '영화/애니메이션', '2': '자동차', '10': '음악', '15': '동물', '17': '스포츠',
      '19': '여행', '20': '게임', '22': '일상/브이로그', '23': '코미디', '24': '엔터테인먼트',
      '25': '뉴스/정치', '26': '노하우/스타일', '27': '교육', '28': 'IT/기술', '29': '비영리/사회운동'
    };

    const channelMap = {};
    channelRes.data.items.forEach(c => { channelMap[c.id] = parseInt(c.statistics.subscriberCount); });

    const videoDataMap = {};
    videoRes.data.items.forEach(v => { 
      videoDataMap[v.id] = {
        views: parseInt(v.statistics.viewCount),
        catId: v.snippet.categoryId
      };
    });

    const cpmMap = {
      '금융/재테크': 12.0, 'IT/기술': 8.5, '교육': 5.0, '비즈니스': 10.0,
      '일상/브이로그': 2.5, '게임': 1.8, '음악': 1.2, '엔터테인먼트': 3.0, '기타': 2.0
    };

    const enrichedVideos = items
      .filter(item => {
        const isTopic = item.snippet.channelTitle.endsWith(' - Topic');
        const isAutoGenerated = item.snippet.description && item.snippet.description.includes('Auto-generated by YouTube');
        return !isTopic && !isAutoGenerated;
      })
      .map(item => {
        const vData = videoDataMap[item.id.videoId] || { views: 0, catId: '22' };
        const views = vData.views;
        const subs = channelMap[item.snippet.channelId] || 1;
        const ratio = parseFloat((views / subs).toFixed(2));
        const category = categoryMap[vData.catId] || '기타';
        
        const growth24h = Math.floor(views * (0.01 + Math.random() * 0.04));
        const velocity = parseFloat((ratio * 0.4 + Math.random() * 2).toFixed(1));
        
        // 트렌드 데이터: ratio가 높으면 우상향 경향성 부여
        const trend = Array.from({ length: 7 }, (_, i) => ({
            v: Math.floor((ratio * 10) + (i * (ratio > 1.5 ? 5 : 2)) + Math.random() * 20)
        }));
        
        const tags = [category, '조회수급상승', ratio > 2.0 ? '폭발적성장' : '안정적'].filter(t => t);
        
        // 카테고리별 CPM 적용 (달러 기준 -> 한국 원화 환산 느낌으로 1000배)
        const cpm = cpmMap[category] || 2.0;
        const estEarnings = Math.floor((views / 1000) * cpm * 1300); // 원화 기준 환산

        return {
          id: item.id.videoId,
          channelId: item.snippet.channelId,
          title: item.snippet.title,
          thumbnail: item.snippet.thumbnails.high.url,
          channelTitle: item.snippet.channelTitle,
          views,
          subscribers: subs,
          ratio,
          publishedAt: item.snippet.publishedAt,
          growth24h,
          velocity,
          trend,
          category,
          tags,
          estEarnings
        };
      }).sort((a, b) => b.ratio - a.ratio);

    // 대상 캐시에 저장 (기본 카테고리면 fixedCache, 일반 검색이면 cache)
    targetCache.set(cacheKey, enrichedVideos);

    res.json(enrichedVideos);
  } catch (error) {
    console.error('API Fetch Error:', error?.response?.data || error.message);
    res.status(500).json({ error: 'Failed to fetch data from YouTube API' });
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server is running closely on http://localhost:${PORT}`);
});
