import express from 'express';
import cors from 'cors';
import axios from 'axios';
import dotenv from 'dotenv';
import { LRUCache } from 'lru-cache';

dotenv.config({ path: '.env.local' });

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3001;
const API_KEY = process.env.VITE_YOUTUBE_API_KEY;

// 기본 제공 카테고리 (캐시에서 밀려나지 않도록 별도 관리)
const defaultQueries = [
  '코딩 브이로그',
  '일상|브이로그|vlog',
  '게임|리뷰|플레이',
  '강아지|고양이|동물',
  '이슈|뉴스|알아보기|꿀팁',
  '먹방|요리|레시피|mukbang',
  '여행|가볼만한곳|핫플'
];

// 고정 캐시: 기본 카테고리는 조회 빈도가 높으므로 밀려나지 않게 따로 저장
const fixedCache = new LRUCache({
  max: 100, // 카테고리 * 시간 조합을 다 합쳐도 100개면 충분
  ttl: 1000 * 60 * 60 * 24, // 24시간
});

// 일반 캐시: 단순 사용자 검색 (1000개 초과 시 오래된 것부터 삭제)
const cache = new LRUCache({
  max: 1000,
  ttl: 1000 * 60 * 60 * 24, // 24시간
});

const getPublishedAfter = (p) => {
  const d = new Date();
  if (p === '1w') d.setDate(d.getDate() - 7);
  else if (p === '1m') d.setMonth(d.getMonth() - 1);
  else if (p === '3m') d.setMonth(d.getMonth() - 3);
  else return null;
  return d.toISOString();
};

app.get('/api/videos', async (req, res) => {
  const { searchQuery, overridePeriod } = req.query;

  if (!searchQuery) {
    return res.status(400).json({ error: 'searchQuery is required' });
  }

  if (!API_KEY) {
    return res.status(500).json({ error: 'YouTube API Key is missing on the server' });
  }

  const cacheKey = `${searchQuery}_${overridePeriod}`;
  
  // 기본 카테고리인지 확인하고 캐시를 나눔
  const isDefaultQuery = defaultQueries.includes(searchQuery);
  const targetCache = isDefaultQuery ? fixedCache : cache;
  
  const cachedData = targetCache.get(cacheKey);
  if (cachedData) {
    console.log(`[Cache Hit] ${cacheKey} (Target: ${isDefaultQuery ? 'Fixed' : 'Normal'}, Size: ${targetCache.size})`);
    return res.json(cachedData);
  }

  console.log(`[Cache Miss] Fetching data for: ${cacheKey}`);

  try {
    const publishedAfter = getPublishedAfter(overridePeriod);
    const searchParams = { part: 'snippet', q: searchQuery, maxResults: 50, type: 'video', key: API_KEY };
    if (publishedAfter) searchParams.publishedAfter = publishedAfter;

    const searchRes = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: searchParams
    });
    const items = searchRes.data.items || [];

    if (items.length === 0) {
      return res.json([]);
    }

    const videoIds = items.map(item => item.id.videoId).join(',');
    const channelIds = [...new Set(items.map(item => item.snippet.channelId))].join(',');

    const videoRes = await axios.get('https://www.googleapis.com/youtube/v3/videos', {
      params: { part: 'statistics', id: videoIds, key: API_KEY }
    });
    const channelRes = await axios.get('https://www.googleapis.com/youtube/v3/channels', {
      params: { part: 'statistics', id: channelIds, key: API_KEY }
    });

    const channelMap = {};
    channelRes.data.items.forEach(c => { channelMap[c.id] = parseInt(c.statistics.subscriberCount); });

    const statsMap = {};
    videoRes.data.items.forEach(v => { statsMap[v.id] = parseInt(v.statistics.viewCount); });

    const enrichedVideos = items
      .filter(item => {
        const isTopic = item.snippet.channelTitle.endsWith(' - Topic');
        const isAutoGenerated = item.snippet.description && item.snippet.description.includes('Auto-generated by YouTube');
        return !isTopic && !isAutoGenerated;
      })
      .map(item => {
        const views = statsMap[item.id.videoId] || 0;
        const subs = channelMap[item.snippet.channelId] || 1;
        return {
          id: item.id.videoId,
          title: item.snippet.title,
          thumbnail: item.snippet.thumbnails.high.url,
          channelTitle: item.snippet.channelTitle,
          views,
          subscribers: subs,
          ratio: parseFloat((views / subs).toFixed(2)),
          publishedAt: item.snippet.publishedAt
        };
      }).sort((a, b) => b.ratio - a.ratio);

    // 대상 캐시에 저장 (기본 카테고리면 fixedCache, 일반 검색이면 cache)
    targetCache.set(cacheKey, enrichedVideos);

    res.json(enrichedVideos);
  } catch (error) {
    console.error('API Fetch Error:', error?.response?.data || error.message);
    res.status(500).json({ error: 'Failed to fetch data from YouTube API' });
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server is running closely on http://localhost:${PORT}`);
});
